### ISSUE TITLE
[FEATURE] Crinos health tracker update

### ISSUE THREAD

**Issue by Veilza** [Rayji96/foundry-V5#210]
As it is now, the Crinos health display is doomed to awkwardly sit beside or under the normal health display. However, I plan to fix this by merging the Crinos health and the normal health on the Werewolf sheet so that it can be displayed without issue, and in addition, enable it to automatically transfer any Crinos health damage onto the normal health tracker.

Therefore, the following goals to resolve this issue would be:

- [ ] Move Crinos health tracker to display with the normal health tracker instead of beside or below.
- [ ] Allow Crinos health to automatically transfer any damage in those boxes to the normal health tracker (with the option to disable this functionality if the storyteller desires.)
- [ ] A migration function might be required if I'm to merge health and Crinos health together; but, if I can avoid doing this and instead only update the way the sheet displays the health, then no migration function would be necessary.
