### ISSUE TITLE
[FEATURE] Dice Backend Rework

### ISSUE THREAD

**Issue by Veilza** [Rayji96/foundry-V5#234]
(This is an issue mainly for the sake of keeping track of other ones and features that will be included alongside them.)

The dice backend is currently very messy--three different files for the different splats and they all use a messy system for defining variables to be passed to rolls. Here's what will be changing with the dice backend rework:

- [x] Unify all dicerolls to be called from a single file and function
- [x] Make all rolls across all sheets prompt a roll dialogue with the ability to add attributes/skills/disciplines/etc as desired (Related issues: #115, #244)
- [x] Pass data through an object rather than as separate variables
- [x] Allow macros to be executed following a roll (Related issue: #69)
- [x] Allow for situational modifiers to be included in the roll dialogue (Related issues: #202, #138, #65)
- [x] Implement an API for macros and other modules to access the diceroller code
